version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions: # Code Deploy 에서 EC2 서버로 넘겨준 파일 모두 ec2-user 권한을 갖게 함
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # Code Deploy 배포 단계에서 실행될 명령어 지정
  AfterInstall:
    - location: stop.sh # nginx 와 연결되어 있지 않은 스프링 부트를 종료한다.
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh # nginx 와 연결되어 있지 않은 Port 로 새 버전의 스프링 부트를 시작한다.
      timeout: 90 # 스크립트가 90초 이상 실행되면 실패로 간주하고 수행 종료시킴
      runas: ec2-user

  ValidateService:
    - location: health.sh # 새 스프링 부트가 정삭적으로 실행됐는지 확인한다.
      timeout: 60
      runas: ec2-user
